# Set this to true if your ranking system uses a prestige system 
# EX: You start at E-lvl recruit rank to E-Lvl brigadier then reset to D-Lvl recruit
prestige: true

# levels for your prestige if used, otherwise ignore this section.
# EX: For E-Lvl I use e. If I wanted a prestige called High I could use high.
prestigeLevls:
    lvl1: e
	lvl2: d
	lvl3: c
	lvl4: b
	lvl5: a
	lvl6: s
	lvl7: ss
    
# Money needed for prestige true or false
prestigeMoney: true

# Set this false if you will charge the same amount for each prestige, true if you want a dynamic amount
presMonChange: false

# Money amount for constant amount
presMonConst: 320000

# Money for dynamic amount. If the number of amounts here is less than the number of prestiges
# the last number will be used for subsequent prestiges. Each level should simply increase by one. 
# number gaps will work. I.e. lvl1: 10 followed by lvl4 30. Levels 2 and 3 will use the value for level 1.
# This section is only even looked at if presMonChange is set to true.
presMonDyn:
    lvl1: 100000
	lvl2: 200000
	lvl3: 300000

# List of your ranks that will be used for the permissions check. Ranks listed in ascending order and the top rank is used only for prestige.
# i.e. no time check for E-Lvl brigadier to D-lvl recruit or D-Lvl brigadier to C-lvl recruit and so on.
ranks:
    - recruit
    - corporal
    - sergeant
    - lieutenant
    - major
    - colonel
    - brigadier

# requirements for the ranks should be in this format. lvl can be ignored if not using prestige. Time should be in minutes.
# non-prestige example:
# corporal:
#   money: $$$$
#   time: ####
rankReq:
	corporal:
		lvl1: e
			money: $$$$
			time: ####
		lvl2: d
			money: $$$$
			time: ####

# How will your permission for the ranks look? r = rank and p = prestige
# default is rp. The permission would look like rank.prestige EX: corporal.e
#valid options are r, rp, and pr. Use just r if and only if you aren't using prestiges.
permSetUp: rp